default: &default
  site_name: "Sample App"
  admin_email: "admin@example.com"
  digit_10: 10
  image_content_types:
    - image/jpeg
    - image/gif
    - image/png
  image_accept_format: "image/jpeg,image/gif,image/png"

development:
  <<: *default

production:
  <<: *default
  site_name: "Sample App"

mailer:
  from: "noreply@example.com"

placeholder:
  date_time: "yyyy/mm/dd"
